const constants = {
  SELECTED_PROJECTS: "SELECTED_PROJECTS",
  ARCHITECTURE_PROJECTS: "ARCHITECTURE_PROJECTS",
  CONSTRUCTION_PROJECTS: "CONSTRUCTION_PROJECTS",
  INTERIOR_PROJECTS: "INTERIOR_PROJECTS"
};

export default constants;
