const constants = {
  SELECTED_PROJECT: "SELECTED_PROJECT",
  ARCHITECTURE_PROJECTS: "ARCHITECTURE_PROJECTS",
  CONSTRUCTION_PROJECTS: "CONSTRUCTION_PROJECTS",
  INTERIOR_PROJECTS: "INTERIOR_PROJECTS",
  PROJECT_DETAILS: "PROJECT_DETAILS",
  BASE_URL: "https://ykd-serv.herokuapp.com",
  PROJECTS_PATH: "/apis/projects/"
};

export default constants;
